services:
  backend:
    build: 
      context: ./hairfit_server
    volumes:
      - db_data:/app/db
      - uploads_data:/app/uploads
      - assets_data:/app/assets/styles
    env_file:
      - ./hairfit_server/.env
    environment:
      - SQLALCHEMY_DATABASE_URL=sqlite:///./db/hairfit.db
      - ALLOWED_ORIGINS=*
    command: >
      sh -c "mkdir -p db && uvicorn main:app --host 0.0.0.0 --port 8000"
    restart: always
    networks:
      - akke
    
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    depends_on:
      - backend
    restart: always
    networks:
      - akke

volumes:
  db_data:
  uploads_data:
  assets_data:


networks:
  akke:
    external: true
